package com.meal.common.mapper;

import com.meal.common.dto.MealGoods;
import com.meal.common.dto.MealGoodsExample;
import java.util.List;

import com.meal.common.dto.MealShop;
import com.meal.common.model.ShopRequestVo;
import com.meal.common.model.WxGoodsVo;
import org.apache.ibatis.annotations.Param;

public interface MealGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_goods
     *
     * @mbg.generated
     */
    long countByExample(MealGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_goods
     *
     * @mbg.generated
     */
    int deleteByExample(MealGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_goods
     *
     * @mbg.generated
     */
    int insert(MealGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_goods
     *
     * @mbg.generated
     */
    int insertSelective(MealGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_goods
     *
     * @mbg.generated
     */
    MealGoods selectOneByExample(MealGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_goods
     *
     * @mbg.generated
     */
    MealGoods selectOneByExampleSelective(@Param("example") MealGoodsExample example, @Param("selective") MealGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_goods
     *
     * @mbg.generated
     */
    MealGoods selectOneByExampleWithBLOBs(MealGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_goods
     *
     * @mbg.generated
     */
    List<MealGoods> selectByExampleSelective(@Param("example") MealGoodsExample example, @Param("selective") MealGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_goods
     *
     * @mbg.generated
     */
    List<MealGoods> selectByExampleWithBLOBs(MealGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_goods
     *
     * @mbg.generated
     */
    List<MealGoods> selectByExample(MealGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_goods
     *
     * @mbg.generated
     */
    MealGoods selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") MealGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_goods
     *
     * @mbg.generated
     */
    MealGoods selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_goods
     *
     * @mbg.generated
     */
    MealGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Long id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MealGoods record, @Param("example") MealGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_goods
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") MealGoods record, @Param("example") MealGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MealGoods record, @Param("example") MealGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MealGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(MealGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MealGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MealGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Long id);

    List<MealGoods> findMany(@Param("request") WxGoodsVo request, @Param("limit") Integer limit, @Param("offset") Long offset);

}
