package com.meal.common.mapper;

import com.meal.common.dto.MealMenu;
import com.meal.common.dto.MealMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MealMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_menu
     *
     * @mbg.generated
     */
    long countByExample(MealMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_menu
     *
     * @mbg.generated
     */
    int deleteByExample(MealMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_menu
     *
     * @mbg.generated
     */
    int insert(MealMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_menu
     *
     * @mbg.generated
     */
    int insertSelective(MealMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_menu
     *
     * @mbg.generated
     */
    MealMenu selectOneByExample(MealMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_menu
     *
     * @mbg.generated
     */
    MealMenu selectOneByExampleSelective(@Param("example") MealMenuExample example, @Param("selective") MealMenu.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_menu
     *
     * @mbg.generated
     */
    List<MealMenu> selectByExampleSelective(@Param("example") MealMenuExample example, @Param("selective") MealMenu.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_menu
     *
     * @mbg.generated
     */
    List<MealMenu> selectByExample(MealMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_menu
     *
     * @mbg.generated
     */
    MealMenu selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") MealMenu.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_menu
     *
     * @mbg.generated
     */
    MealMenu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MealMenu record, @Param("example") MealMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MealMenu record, @Param("example") MealMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MealMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MealMenu record);
}