package com.meal.common.mapper;

import com.meal.common.dto.MealBanner;
import com.meal.common.dto.MealBannerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MealBannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_banner
     *
     * @mbg.generated
     */
    long countByExample(MealBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_banner
     *
     * @mbg.generated
     */
    int deleteByExample(MealBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_banner
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_banner
     *
     * @mbg.generated
     */
    int insert(MealBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_banner
     *
     * @mbg.generated
     */
    int insertSelective(MealBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_banner
     *
     * @mbg.generated
     */
    MealBanner selectOneByExample(MealBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_banner
     *
     * @mbg.generated
     */
    MealBanner selectOneByExampleSelective(@Param("example") MealBannerExample example, @Param("selective") MealBanner.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_banner
     *
     * @mbg.generated
     */
    List<MealBanner> selectByExampleSelective(@Param("example") MealBannerExample example, @Param("selective") MealBanner.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_banner
     *
     * @mbg.generated
     */
    List<MealBanner> selectByExample(MealBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_banner
     *
     * @mbg.generated
     */
    MealBanner selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") MealBanner.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_banner
     *
     * @mbg.generated
     */
    MealBanner selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_banner
     *
     * @mbg.generated
     */
    MealBanner selectByPrimaryKeyWithLogicalDelete(@Param("id") Long id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_banner
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MealBanner record, @Param("example") MealBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_banner
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MealBanner record, @Param("example") MealBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_banner
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MealBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_banner
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MealBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_banner
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MealBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_banner
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Long id);
}