package com.meal.common.mapper;

import com.meal.common.dto.MealOrderWx;
import com.meal.common.dto.MealOrderWxExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MealOrderWxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    long countByExample(MealOrderWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    int deleteByExample(MealOrderWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    int insert(MealOrderWx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    int insertSelective(MealOrderWx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    MealOrderWx selectOneByExample(MealOrderWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    MealOrderWx selectOneByExampleSelective(@Param("example") MealOrderWxExample example, @Param("selective") MealOrderWx.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    List<MealOrderWx> selectByExampleSelective(@Param("example") MealOrderWxExample example, @Param("selective") MealOrderWx.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    List<MealOrderWx> selectByExample(MealOrderWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    MealOrderWx selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") MealOrderWx.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    MealOrderWx selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    MealOrderWx selectByPrimaryKeyWithLogicalDelete(@Param("id") Long id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MealOrderWx record, @Param("example") MealOrderWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MealOrderWx record, @Param("example") MealOrderWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MealOrderWx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MealOrderWx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MealOrderWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Long id);
}