package com.meal.common.mapper;

import com.meal.common.dto.MealUserShop;
import com.meal.common.dto.MealUserShopExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MealUserShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_user_shop
     *
     * @mbg.generated
     */
    long countByExample(MealUserShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_user_shop
     *
     * @mbg.generated
     */
    int deleteByExample(MealUserShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_user_shop
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_user_shop
     *
     * @mbg.generated
     */
    int insert(MealUserShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_user_shop
     *
     * @mbg.generated
     */
    int insertSelective(MealUserShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_user_shop
     *
     * @mbg.generated
     */
    MealUserShop selectOneByExample(MealUserShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_user_shop
     *
     * @mbg.generated
     */
    MealUserShop selectOneByExampleSelective(@Param("example") MealUserShopExample example, @Param("selective") MealUserShop.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_user_shop
     *
     * @mbg.generated
     */
    List<MealUserShop> selectByExampleSelective(@Param("example") MealUserShopExample example, @Param("selective") MealUserShop.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_user_shop
     *
     * @mbg.generated
     */
    List<MealUserShop> selectByExample(MealUserShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_user_shop
     *
     * @mbg.generated
     */
    MealUserShop selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") MealUserShop.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_user_shop
     *
     * @mbg.generated
     */
    MealUserShop selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_user_shop
     *
     * @mbg.generated
     */
    MealUserShop selectByPrimaryKeyWithLogicalDelete(@Param("id") Long id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_user_shop
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MealUserShop record, @Param("example") MealUserShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_user_shop
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MealUserShop record, @Param("example") MealUserShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_user_shop
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MealUserShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_user_shop
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MealUserShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_user_shop
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MealUserShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_user_shop
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Long id);
}