package com.meal.common.mapper;

import com.meal.common.dto.MealOrderWx;
import com.meal.common.dto.MealOrderWxExample;
import com.meal.common.dto.MealOrderWxWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MealOrderWxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    long countByExample(MealOrderWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    int deleteByExample(MealOrderWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    int insert(MealOrderWxWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    int insertSelective(MealOrderWxWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    MealOrderWx selectOneByExample(MealOrderWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    MealOrderWxWithBLOBs selectOneByExampleSelective(@Param("example") MealOrderWxExample example, @Param("selective") MealOrderWxWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    MealOrderWxWithBLOBs selectOneByExampleWithBLOBs(MealOrderWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    List<MealOrderWxWithBLOBs> selectByExampleSelective(@Param("example") MealOrderWxExample example, @Param("selective") MealOrderWxWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    List<MealOrderWxWithBLOBs> selectByExampleWithBLOBs(MealOrderWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    List<MealOrderWx> selectByExample(MealOrderWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    MealOrderWxWithBLOBs selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") MealOrderWxWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    MealOrderWxWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    MealOrderWxWithBLOBs selectByPrimaryKeyWithLogicalDelete(@Param("id") Long id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MealOrderWxWithBLOBs record, @Param("example") MealOrderWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") MealOrderWxWithBLOBs record, @Param("example") MealOrderWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MealOrderWx record, @Param("example") MealOrderWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MealOrderWxWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(MealOrderWxWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MealOrderWx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MealOrderWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meal_order_wx
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Long id);
}