POST {{host}}/wx/auth/register
Content-Type: application/json

{
  "code": "123456",
  "username": "13876410945",
  "nickname": "test21",
  "password": "123456783",
  "mobile": "13876410945"
}

###

POST {{host}}/wx/auth/login
Content-Type: application/json

{
  "phoneNumber": "13876410945",
  "password": "123456783",
  "type": "1",
  "code": "1212"
}

###

POST {{host}}/wx/auth/refresh
Authorization:  {{token}}

###
GET  {{host}}/wx/auth
Authorization: {{token}}

###
POST {{host}}/wx/shop/list
Authorization:  {{token}}
Content-Type: application/json

{
  "shopId" :6
}


###
POST {{host}}/wx/goods
Authorization:  {{token}}
Content-Type: application/json

{
  "shopId": 6,
  "page": 1,
  "limit": 10
}

###
POST {{host}}/wx/goods/little
Authorization:  {{token}}
Content-Type: application/json

{
  "shopId": 6
}

###
POST {{host}}/wx/cart/add
Authorization:  {{token}}
Content-Type: application/json

{
  "shopId": 6,
  "goods": [
    {
      "goodsId": "1181007",
      "goodsSn": "1181007",
      "goodsName": "辣椒炒肉饭",
      "checked": "true",
      "number": "2",
      "cartCalamityVos": [
        {
          "calamityId": 299,
          "calamityName": "酸梅汁",
          "calamityNumber": 2
        }
      ]
    },
    {
      "goodsId": "1181011",
      "goodsSn": "1181011",
      "goodsName": "烧鸭饭",
      "checked": "true",
      "number": "1"
    },
    {
      "goodsId": "1181102",
      "goodsSn": "1181102",
      "goodsName": "蛋肠粉",
      "checked": "true",
      "number": "1"
    },
    {
      "goodsId": "1181103",
      "goodsSn": "1181103",
      "goodsName": "炒米粉",
      "checked": "true",
      "number": "1"
    }
  ]
}


###
GET  {{host}}/wx/cart/amount?shopId=6
Authorization: {{token}}

###
GET  {{host}}/wx/cart?shopId=6
Authorization: {{token}}

###
POST  {{host}}/wx/cart/delete?shopId=6
Authorization: {{token}}

###
GET  {{host}}/wx/category?shopId=6&isTimeOnSale=2
Authorization: {{token}}

###
GET  {{host}}/wx/banner
Authorization: {{token}}

###
GET  {{host}}/wx/auth/bind/1046003
Authorization: {{token}}

###

POST {{host}}/wx/auth/loginByWx
Content-Type: application/json

{
  "code": "081tg80w33Fcf03BdE0w3RMpmP3tg80j",
  "encryptedData": "g+GpXedQ0bQG/mg1pzs1bE544DNrC0fWg2M9pDq/dWpqbKk9Yi67h0Kl7B3KEdZhvy9ASdsSkAvARrGOzAFZ81IQz39RzYDm/bnfPx9YNHNRFxoymq8xpMWY8pJsp6px6NDDBYpuM3h4dGSAMx0KcvO1hOWZuGo3c8G1iPFIyNXAQDsPc4ugEGhj90DyCtqRz4Wp5BhFxC5xk3R1gnDP9BEarGkm7VioQqRCk3DavfY2d4/VfY5eN52+Lbn5wvyRwbvEEO4KVdA6eGOvZe2E0tauCutGYSLnCo5d0CUvLAYJZsgnkc1/SpK2zbfDFTnTzl4cCGsR2NlNFGaIbVFFLh6xKyIKuKXz54PK2oETAbZhkdxxNR33c7VcujFTO75w9xL9FPEoWdTs4DKDlUwQ2TJXZd7F8ClX6uxx5/yhFA/MYN7p4iWfaVzcI+kjoAq6ntvGR0ekljK+8FlT65duZA==",
  "iv": "dpRIcbq8B1H/HJoKkTPbXg==",
  "codePhone": "d9ac9bb37a8d9c1e7e3191eafe7df8c11e6d2c2c8adaa1d582077abe062404e6"
}

###
POST {{host}}/wx/order/submit
Content-Type: application/json
Authorization: {{token}}

{
  "shopId": 6,
  "message": "请尽快送达",
  "orders": [
    {
      "goods": [
        {
          "goodsId": 1181007,
          "number": 2,
          "price": 10.00,
          "cartCalamityVos": [
            {
              "calamityId": 299,
              "calamityNumber": 1,
              "price": 0.00
            }
          ]
        },
        {
          "goodsId": 1181011,
          "number": 1,
          "price": 10.00,
          "cartCalamityVos": [
            {
              "calamityId": 298,
              "calamityNumber": 2,
              "price": 0.00
            }
          ]
        }
      ],
      "orderPrice": 30.00,
      "actualPrice": 30.00,
      "isTimeOnSale": 2
    },
    {
      "goods": [
        {
          "goodsId": 1181102,
          "number": 2,
          "price": 5.00,
          "cartCalamityVos": [
            {
              "calamityId": 257,
              "calamityNumber": 1,
              "price": 0.00
            }
          ]
        }
      ],
      "orderPrice": 10.00,
      "actualPrice": 10.00,
      "isTimeOnSale": 1
    }
  ],
  "orderPrice": 40.00,
  "actualPrice": 40.00
}

###
#GET {{host}}/wx/order/detail?orderSn=mealnkAa5A4Mgff0GP
GET {{host}}/wx/order/detail
Content-Type: application/json
Authorization: {{token}}

###
POST  {{host}}/wx/order/prepay/mealnkAa5A4Mgff0GP
Authorization: {{token}}
