POST http://localhost:9001/wx/auth/register
Content-Type: application/json

{
  "code": "123456",
  "username":"13566410996",
  "nickname":"test1",
  "password": "123456783",
  "mobile": "13566410996"
}
###

POST http://localhost:9001/wx/auth/login
Content-Type: application/json

{
  "phoneNumber": "13566410996",
  "password": "123456783",
  "type": "1"
}
###

POST http://localhost:9001/wx/auth/refresh
Authorization:  {{token}}

###
GET  http://localhost:9001/wx/auth
Authorization: {{token}}
###
POST http://localhost:9001/wx/shop/list?page=1&limit=10
Authorization:  {{token}}
