POST http://localhost:9001/wx/auth/register
Content-Type: application/json

{
  "code": "123456",
  "username":"15566410836",
  "nickname":"ebi不要1233",
  "password": "123456783",
  "mobile": "15566410836"
}
###

POST http://localhost:9001/wx/auth/login
Content-Type: application/json

{
  "phoneNumber": "15566310836",
  "password": "12345678",
  "type": "1"
}
###

POST http://localhost:9001/wx/auth/refresh
Authorization:  {{token}}

###
GET  http://localhost:9001/wx/auth
Authorization: {{token}}
