logging:
  level:
    root: info
    org:
      springframework:
        web:
          reactive:
            function:
              client: info
    com:
      meal: debug

meal:
  wx:
    miniapp:
      configs:
        appid: "wxff1a8500e8238674"
        appSecret: "a98a0f28b4edd080950b3bed61bcf881"
        token: #微信小程序消息服务器配置的token
        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON
server:
  port: 9001
