spring:

mybatis:
  configuration:
    # mybatis开启驼峰字段名解析为 _ 符号
    map-underscore-to-camel-case: true
  # mapper的xml路径
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    root: info
    org:
      springframework:
        web:
          reactive:
            function:
              client: info
    com:
      meal: debug
pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql
meal:
  wx:
  miniapp:
    configs:
        appid: #微信小程序的appid
        secret: #微信小程序的Secret
        token: #微信小程序消息服务器配置的token
        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON
server:
  port: 9001
