logging:
  level:
    root: info
    org:
      springframework:
        web:
          reactive:
            function:
              client: info
    com:
      meal: debug

meal:
  wx:
    miniapp:
      configs:
        appid: "wxff1a8500e8238674"
        appSecret: "a98a0f28b4edd080950b3bed61bcf881"
        token: #微信小程序消息服务器配置的token
        aesKey: "fn2u4f5ty7huhf932hfhi4u3fh23rf3t"
        mch-id: "1640664276"
        mch-key: "ffiuq3hu34ufiuq4f3o4vi4r234fv425"
        notify-url: "https://yangyua.com/wx/order/pay-notify"
        refund-notify-url: "https://yangyua.com/wx/order/refund-notify"
        api-v3-key: "fn2u4f5ty7huhf932hfhi4u3fh23rf3t"
        key-path: "classpath:/cert/apiclient_cert.p12"
        msgDataFormat: JSON
        breakfast_id: "z3WB96pX2ASunRRQRcaBh7ccDNwa2E2NU4R4Gp5mYXg"
        lunch_id: "z3WB96pX2ASunRRQRcaBhz8hR8ewwtURe1D2JbQkvKk"
        dinner_id: "z3WB96pX2ASunRRQRcaBhyDYxInZafMObx1M-cPbKTQ"
  webclient:
    enable: true
    load-balance: true
server:
  port: 9001
