logging:
  level:
    root: info
    org:
      springframework:
        web:
          reactive:
            function:
              client: info
    com:
      meal: debug


#meal:
#  wx:
#    miniapp:
#      configs:
#          appid: #微信小程序的appid
#          secret: #微信小程序的Secret
#          token: #微信小程序消息服务器配置的token
#          aesKey: #微信小程序消息服务器配置的EncodingAESKey
#          msgDataFormat: JSON
server:
  port: 9001
