pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/meal?characterEncoding=UTF-8&useUnicode=true&connectionTimeZone=LOCAL&forceConnectionTimeZoneToSession=true
    username: root
    password: 123456
  # redis相关配置
  redis:
    # 配置主机
    host: 127.0.0.1
    # 配置使用的数据库
    database: 0
    # 指定端口
    port: 6379
#    # 密码
#    password: 123456
mybatis:
  configuration:
    # mybatis开启驼峰字段名解析为 _ 符号
    map-underscore-to-camel-case: true
  # mapper的xml路径
  mapper-locations: classpath:mapper/*.xml
# jwt配置
jwt:
  # 请求头
  tokenHeader: Authorization
  # 签名加盐
  secret: meal_e_b
  # jwt过期时间
  expiration: 18000
  # jwt刷新时间
  refreshExpiration: 604800
  # token头部
  tokenHead: 'Bearer '
meal:
  mail:
    # 邮件通知配置,邮箱一般用于接收业务通知例如收到新的订单，sendto 定义邮件接收者，通常为商城运营人员
    enable: false
    host: smtp.exmail.qq.com
    username: ex@ex.com.cn
    password: XXXXXXXXXXXXX
    sendfrom: ex@ex.com.cn
    sendto: ex@qq.com
    port: 465
    # 短消息模版通知配置
    # 短信息用于通知客户，例如发货短信通知，注意配置格式；template-name，template-templateId 请参考 NotifyType 枚举值
  sms:
    sign: meal
    templateCode: 123
    aliyun:
      regionId: xxx
      accessKeyId: xxx
      accessKeySecret: xxx
