pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      webStatFilter:
        enabled: true
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
    url:  jdbc:mysql://119.23.237.39:3306/meal?characterEncoding=UTF-8&useUnicode=trueGMT&serverTimezone=GMT
    username: root
    password: qqww1122
  # redis相关配置
  redis:
    # 配置主机
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

#    # 密码
#    password: 123456
mybatis:
  configuration:
    # mybatis开启驼峰字段名解析为 _ 符号
    map-underscore-to-camel-case: true
  # mapper的xml路径
  mapper-locations: classpath:mapper/*.xml
# jwt配置
jwt:
  # 请求头
  tokenHeader: Authorization
  # 签名加盐
  secret: meal_e_b
  # jwt过期时间
  expiration: 3600
  # jwt刷新时间
  refreshExpiration: 36000
  # token头部
  tokenHead: 'Bearer '
meal:
  mail:
    # 邮件通知配置,邮箱一般用于接收业务通知例如收到新的订单，sendto 定义邮件接收者，通常为商城运营人员
    enable: false
    host: smtp.exmail.qq.com
    username: ex@ex.com.cn
    password: XXXXXXXXXXXXX
    sendfrom: ex@ex.com.cn
    sendto: ex@qq.com
    port: 465
    # 短消息模版通知配置
    # 短信息用于通知客户，例如发货短信通知，注意配置格式；template-name，template-templateId 请参考 NotifyType 枚举值
  sms:
    sign: meal
    templateCode: 123
    aliyun:
      regionId: xxx
      accessKeyId: xxx
      accessKeySecret: xxx
