pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/meal?characterEncoding=UTF-8&useUnicode=true&connectionTimeZone=LOCAL&forceConnectionTimeZoneToSession=true
    username: root
    password: 123456
mybatis:
  configuration:
    # mybatis开启驼峰字段名解析为 _ 符号
    map-underscore-to-camel-case: true
  # mapper的xml路径
  mapper-locations: classpath:mapper/*.xml
