package com.meal.common.model;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Positive;
import java.util.List;

public class ShoppingCartVo {
    @NotNull
    private  Long goodsId;
    @NotBlank
    private  String goodsName;
    @NotBlank
    private  String goodsSn;
    @NotBlank
    private  Boolean checked;
    @Positive
    private  Long number;

    private List<CartCalamityVo> calamityVos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meal_cart.calamity_name
     *
     * @mbg.generated
     */


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meal_cart.calamity_number
     *
     * @mbg.generated
     */


    public Long getGoodsId() {
        return goodsId;
    }

    public ShoppingCartVo setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
        return this;
    }

    public String getGoodsSn() {
        return goodsSn;
    }

    public ShoppingCartVo setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn;
        return this;
    }


    public Long getNumber() {
        return number;
    }

    public ShoppingCartVo setNumber(Long number) {
        this.number = number;
        return this;
    }

    public Boolean getChecked() {
        return checked;
    }

    public ShoppingCartVo setChecked(Boolean checked) {
        this.checked = checked;
        return this;
    }

    public String getGoodsName() {
        return goodsName;
    }

    public ShoppingCartVo setGoodsName(String goodsName) {
        this.goodsName = goodsName;
        return this;
    }

    public List<CartCalamityVo> getCalamityVos() {
        return calamityVos;
    }

    public ShoppingCartVo setCalamityVos(List<CartCalamityVo> calamityVos) {
        this.calamityVos = calamityVos;
        return this;
    }
}
