package com.meal.common.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.time.LocalDateTime;
import java.time.LocalTime;

public class ShopResponseVo {
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meal_shop.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meal_shop.desc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meal_shop.pic_url
     *
     * @mbg.generated
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meal_shop.sort_order
     *
     * @mbg.generated
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meal_shop.add_time
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime addTime;
    @JsonFormat(pattern = "HH:mm:ss")
    private LocalTime startTime;
    @JsonFormat(pattern = "HH:mm:ss")
    private  LocalTime endTime;

    public Long getId() {
        return id;
    }

    public ShopResponseVo setId(Long id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return name;
    }

    public ShopResponseVo setName(String name) {
        this.name = name;
        return this;
    }

    public String getDesc() {
        return desc;
    }

    public ShopResponseVo setDesc(String desc) {
        this.desc = desc;
        return this;
    }

    public String getPicUrl() {
        return picUrl;
    }

    public ShopResponseVo setPicUrl(String picUrl) {
        this.picUrl = picUrl;
        return this;
    }

    public Integer getSortOrder() {
        return sortOrder;
    }

    public ShopResponseVo setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
        return this;
    }

    public LocalDateTime getAddTime() {
        return addTime;
    }

    public ShopResponseVo setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
        return this;
    }

    public LocalTime getStartTime() {
        return startTime;
    }

    public ShopResponseVo setStartTime(LocalTime startTime) {
        this.startTime = startTime;
        return this;
    }

    public LocalTime getEndTime() {
        return endTime;
    }

    public ShopResponseVo setEndTime(LocalTime endTime) {
        this.endTime = endTime;
        return this;
    }
}
