package com.meal.common.model;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Positive;

public class ShoppingCartVo {
    private  Long goodsId;
    private  String goodsSn;

    private  Boolean checked;

    private  Long number;

    private Long calamityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meal_cart.calamity_name
     *
     * @mbg.generated
     */

    private String calamityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meal_cart.calamity_number
     *
     * @mbg.generated
     */

    private Long calamityNumber;

    public Long getGoodsId() {
        return goodsId;
    }

    public ShoppingCartVo setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
        return this;
    }

    public String getGoodsSn() {
        return goodsSn;
    }

    public ShoppingCartVo setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn;
        return this;
    }


    public Long getNumber() {
        return number;
    }

    public ShoppingCartVo setNumber(Long number) {
        this.number = number;
        return this;
    }

    public Boolean getChecked() {
        return checked;
    }

    public ShoppingCartVo setChecked(Boolean checked) {
        this.checked = checked;
        return this;
    }

    public Long getCalamityId() {
        return calamityId;
    }

    public ShoppingCartVo setCalamityId(Long calamityId) {
        this.calamityId = calamityId;
        return this;
    }

    public String getCalamityName() {
        return calamityName;
    }

    public ShoppingCartVo setCalamityName(String calamityName) {
        this.calamityName = calamityName;
        return this;
    }

    public Long getCalamityNumber() {
        return calamityNumber;
    }

    public ShoppingCartVo setCalamityNumber(Long calamityNumber) {
        this.calamityNumber = calamityNumber;
        return this;
    }
}
