package com.meal.common.model;

import java.math.BigDecimal;

public class WxLittleCalamityResponseVo {
    private Long calamityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meal_little_calamity.name
     *
     * @mbg.generated
     */
    private String calamityName;

    private Long goodsId;

    private String picUrl;

    private Long shopId;
    private String brief;

    private String unit;

    private BigDecimal price;

    private Integer isTimeOnSale;
    private Boolean isOnSale;



    public Long getGoodsId() {
        return goodsId;
    }

    public WxLittleCalamityResponseVo setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
        return this;
    }

    public String getPicUrl() {
        return picUrl;
    }

    public WxLittleCalamityResponseVo setPicUrl(String picUrl) {
        this.picUrl = picUrl;
        return this;
    }

    public Long getShopId() {
        return shopId;
    }

    public WxLittleCalamityResponseVo setShopId(Long shopId) {
        this.shopId = shopId;
        return this;
    }

    public String getBrief() {
        return brief;
    }

    public WxLittleCalamityResponseVo setBrief(String brief) {
        this.brief = brief;
        return this;
    }

    public String getUnit() {
        return unit;
    }

    public WxLittleCalamityResponseVo setUnit(String unit) {
        this.unit = unit;
        return this;
    }



    public Integer getIsTimeOnSale() {
        return isTimeOnSale;
    }

    public WxLittleCalamityResponseVo setIsTimeOnSale(Integer isTimeOnSale) {
        this.isTimeOnSale = isTimeOnSale;
        return this;
    }

    public Boolean getIsOnSale() {
        return isOnSale;
    }

    public WxLittleCalamityResponseVo setIsOnSale(Boolean onSale) {
        isOnSale = onSale;
        return this;
    }

    public Long getCalamityId() {
        return calamityId;
    }

    public WxLittleCalamityResponseVo setCalamityId(Long calamityId) {
        this.calamityId = calamityId;
        return this;
    }

    public String getCalamityName() {
        return calamityName;
    }

    public WxLittleCalamityResponseVo setCalamityName(String calamityName) {
        this.calamityName = calamityName;
        return this;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public WxLittleCalamityResponseVo setPrice(BigDecimal price) {
        this.price = price;
        return this;
    }

    public Boolean getOnSale() {
        return isOnSale;
    }

    public WxLittleCalamityResponseVo setOnSale(Boolean onSale) {
        isOnSale = onSale;
        return this;
    }
}

